export const ALL_BLOG_REQUEST = "ALL_BLOG_REQUEST"
export const ALL_BLOG_SUCCESS = "ALL_BLOG_SUCCESS"
export const ALL_BLOG_FAILED = "ALL_BLOG_FAILED"

export const BLOG_DETAILS_REQUEST = "BLOG_DETAILS_REQUEST"
export const BLOG_DETAILS_SUCCESS = "BLOG_DETAILS_SUCCESS"
export const BLOG_DETAILS_FAILED = "BLOG_DETAILS_FAILED"


export const CREATE_BLOG_REQUEST = "CREATE_BLOG_REQUEST"
export const CREATE_BLOG_SUCCESS = "CREATE_BLOG_SUCCESS"
export const CREATE_BLOG_FAILED = "CREATE_BLOG_FAILED"

export const CURRENT_USER_BLOGS_REQUEST = "CURRENT_USER_BLOGS_REQUEST"
export const CURRENT_USER_BLOGS_SUCCESS = "CURRENT_USER_BLOGS_SUCCESS"
export const CURRENT_USER_BLOGS_FAILED = "CURRENT_USER_BLOGS_FAILED"

export const DELETE_USER_BLOG_REQUEST = "DELETE_USER_BLOG_REQUEST"
export const DELETE_USER_BLOG_SUCCESS = "DELETE_USER_BLOG_SUCCESS"
export const DELETE_USER_BLOG_FAILED = "DELETE_USER_BLOG_FAILED"

export const UPDATE_USER_BLOG_DATA = "UPDATE_USER_BLOG_DATA"

export const UPDATE_USER_BLOG_REQUEST = "UPDATE_USER_BLOG_REQUEST"
export const UPDATE_USER_BLOG_SUCCESS = "UPDATE_USER_BLOG_SUCCESS"
export const UPDATE_USER_BLOG_FAILED = "UPDATE_USER_BLOG_FAILED"