export const ADD_COMMENT_REQUEST = "ADD_COMMENT_REQUEST"
export const ADD_COMMENT_SUCCESS = "ADD_COMMENT_SUCCESS"
export const ADD_COMMENT_FAILED = "ADD_COMMENT_FAILED"

export const STORE_COMMENT_TO_CURRENT_BLOG_REQUEST = "STORE_COMMENT_TO_CURRENT_BLOG_REQUEST"
export const STORE_COMMENT_TO_CURRENT_BLOG_SUCCESS = "STORE_COMMENT_TO_CURRENT_BLOG_SUCCESS"
export const STORE_COMMENT_TO_CURRENT_BLOG_FAILED = "STORE_COMMENT_TO_CURRENT_BLOG_FAILED" 